apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-env-test
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    app: env-test
