apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apache-ingress
  namespace: promptify2
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  rules:
    - host: apache.local # Replace this with a custom local hostname
      http:
        paths:
          - backend:
              service:
                name: env-test # Make sure this service is running in the 'asd' namespace
                port:
                  number: 80
            path: /
            pathType: Prefix
